apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dockerregistries.fat-controller.test
  annotations:
    kapp.k14s.io/delete-strategy: orphan
spec:
  scope: Namespaced
  group: fat-controller.test
  names:
    plural: dockerregistries
    singular: dockerregistry
    kind: DockerRegistry
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                ingress:
                  type: object
                  required:
                    - host
                  properties:
                    host:
                      type: string
                    secretRef:
                      type: object
                      required:
                        - name
                      properties:
                        name:
                          type: string
                resources:
                  type: object
                  properties:
                    memory:
                      type: string
                      default: 768Mi
                    cpu:
                      type: string
                      default: 250m
                    storage:
                      type: string
                      default: 10Gi
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
