---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: genericlogins.fat-controller.test
  annotations:
    kapp.k14s.io/delete-strategy: orphan
spec:
  scope: Namespaced
  group: fat-controller.test
  names:
    plural: genericlogins
    singular: genericlogin
    kind: GenericLogin
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - credentials
              properties:
                credentials:
                  required:
                  - username
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: object
                      properties:
                        length:
                          type: integer
                          minimum: 0
                          default: 32
                        digits:
                          type: object
                          properties:
                            minimum:
                              type: integer
                              minimum: 0
                        lowercase:
                          type: object
                          properties:
                            minimum:
                              type: integer
                              minimum: 0
                        uppercase:
                          type: object
                          properties:
                            minimum:
                              type: integer
                              minimum: 0
                        symbols:
                          type: object
                          properties:
                            minimum:
                              type: integer
                              minimum: 0
                            charset:
                              type: string
                targetSecret:
                  type: object
                  properties:
                    labels:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                      additionalProperties:
                        type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
