#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Service
metadata:
  name: operator-toolkit
  namespace: #@ data.values.operator.namespace
spec:
  selector:
    deployment: operator-toolkit
  ports:
  #! - port: 8443
  - port: 8080
