---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: dockerregistry.fat-controller.test
spec:
  generateSelector: true
  parentResource:
    apiVersion: fat-controller.test/v1alpha1
    resource: dockerregistries
  childResources:
  - apiVersion: apps/v1
    resource: deployments
    updateStrategy:
      method: InPlace
  - apiVersion: networking.k8s.io/v1
    resource: ingresses
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: persistentvolumeclaims
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: serviceaccounts
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: services
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://operator-toolkit.fat-controller:8080/docker-registry/dockerregistry/sync
