#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: #@ "registry-{}".format(data.values.metadata.name)
  namespace: #@ data.values.metadata.namespace
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: #@ data.values.spec.resources.storage
